# Generated by Django 4.2.5 on 2023-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_vacancy_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
