# Generated by Django 4.2.5 on 2023-09-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_report_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
