# Generated by Django 4.2.5 on 2023-09-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_vacancyapplication_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
