# Generated by Django 4.2.5 on 2023-09-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_vacancyapplication_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='telephone',
            field=models.IntegerField(blank=True),
        ),
    ]
